---
- name: install infrastructure
  sudo: yes
  hosts:
    - selenium
  roles:
    - infrastructure

- name: install infrastructure
  sudo: yes
  hosts:
    - selenium-hub
  roles:
    - selenium-hub

- name: install infrastructure
  sudo: yes
  hosts:
    - selenium-hub
  roles:
    - selenium-node
